---
- rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    - https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
    - https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-AARCH64-RHEL9

- name: setup pgdg packages and dependencies
  ansible.builtin.package:
    name:
      - epel-release
      - "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
